### ISSUE TITLE
Pull starting ease from deck settings instead of config

### ISSUE THREAD

**Issue by brownbat** [brownbat/autoEaseFactor#1]
Currently the "starting ease" option in the config file overrides (ignores?) any starting ease set in deck settings.

The behavior would probably be more expected if it pulled that value from deck settings instead.

(This is lower priority, because there is currently a workaround by using the config, but important QOL long term.)

**Comment by brownbat** [comment]
Fixed.

**Comment by galantra** [comment]
On this occasion, I would like to hint at the add-on [AvgEase](https://ankiweb.net/shared/info/633293039).

**Comment by brownbat** [comment]
Oh nice! I knew ejs had mapped that out in concept, somehow missed that he'd carried it over the finish line. Great to see it.
