### ISSUE TITLE
Error when trying to readjust the ease factor

### ISSUE THREAD

**Issue by ghost** [brownbat/autoEaseFactor#11]
Debug info:
Anki 2.1.22 (0ecc189a) Python 3.8.0 Qt 5.14.1 PyQt 5.14.1
Platform: Windows 10
Flags: frz=True ao=True sv=2
Add-ons, last update check: 2020-09-12 08:39:56

Caught exception:
Traceback (most recent call last):
  File "C:\Users\mario\AppData\Roaming\Anki2\addons21\1672712021\autoEaseFactor.py", line 299, in <lambda>
    did=deck_id: adjust_ease_factors(did))
  File "C:\Users\mario\AppData\Roaming\Anki2\addons21\1672712021\autoEaseFactor.py", line 225, in adjust_ease_factors
    card_ids = mw.col.find_cards(f'deck:"{deck_name}"')
AttributeError: '_Collection' object has no attribute 'find_cards

When I try to readjust the ease factor I get this error

**Comment by ghost** [comment]
I also tried it with anki 2.1.26 I didn't get an error message but anki crashed

**Comment by brownbat** [comment]
Sorry about that, must be from the improvement yesterday, taking a look now...

**Comment by brownbat** [comment]
Ah, they changed the Finder code in 2.1.24, I'll need to create a new version for earlier releases.

I have it working as expected on 2.1.26, though sometimes it can be slow for large decks. How large is your deck?

Would you be willing to help me test a bit more, try the "Export ease factors" function on 2.1.26 and let me know if that's working (it uses the same card searching functions so would help me narrow it down.)

(And if possibly try the "Adjust Ease Factors" option on a small deck, ~100 cards or so, if you have one... it should think for no more than a second, then pop up a dialog that says the operation is complete, depending on your system.)

**Comment by brownbat** [comment]
I've restricted it to only provide those options for 2.1.26+ to prevent the error, but still definitely interested if there are problems with 2.1.26.
