### ISSUE TITLE
Error after updating add-on to recent update; add-on fails to load

### ISSUE THREAD

**Issue by leoleoimn** [brownbat/autoEaseFactor#15]
As the title says, the following pop-up keeps showing up after I recently updated the add-on.

![image](https://user-images.githubusercontent.com/71240029/93034938-44d70880-f66e-11ea-86db-53e4166beb59.png)

Here is the debug info if needed:
    
    Anki 2.1.33 (3f403040) Python 3.8.1 Qt 5.12.6 PyQt 5.12.3
    Platform: Windows 10
    Flags: frz=True ao=True sv=2
    Add-ons, last update check: 2020-09-13 17:28:16
    
    
    ===Add-ons (active)===
    (add-on provided name [Add-on folder, installed at, version, is config changed])
    '' ['No Penalties or Boosting', 0, 'None', '']
    '' ['PassFail (EN)', 0, 'None', '']
    
    ===IDs of active AnkiWeb add-ons===
    
    
    ===Add-ons (inactive)===
    (add-on provided name [Add-on folder, installed at, version, is config changed])
    Auto Ease Factor ['1672712021', 2020-09-12T22:52, 'None', '']

I do want to take note; this problem has persisted since `Anki 2.1.26` and before I've added the `No Penalties or Boosting` and `PassFail (EN)` add-ons. In fact, `Auto Ease Factor` was the only add-on that I had before I added the other two.

I've tried reinstalling the add-on, updating Anki, and even removed `Auto Ease Factor`'s add-on folder and then reinstalling it, but the problem still persists.

**Comment by brownbat** [comment]
A dependency was introduced with the last update, it's been removed, should be good to go.

Sorry about that!

**Comment by leoleoimn** [comment]
Thanks! I can confirm that the error no longer appears.
