### ISSUE TITLE
Error when try to answer a question (ReMemorize)

### ISSUE THREAD

**Issue by aPaci95** [brownbat/autoEaseFactor#18]
If i press spacebar it gives me this error
```
Debug info:
Anki 2.1.26 (70784154) Python 3.8.0 Qt 5.14.1 PyQt 5.14.1
Platform: Windows 10
Flags: frz=True ao=True sv=2
Add-ons, last update check: 2020-10-02 14:31:51

Caught exception:
Traceback (most recent call last):
  File "aqt\webview.py", line 464, in handler
  File "aqt\reviewer.py", line 327, in _onAnswerButton
  File "C:\Users\pacia\AppData\Roaming\Anki2\addons21\1672712021\YesOrNo.py", line 61, in AKR_answerCard
    ease = remap[count][ease]
KeyError: 8
```

If i press 1, 2, 3 or 4 it gives me this error

```
Debug info:
Anki 2.1.26 (70784154) Python 3.8.0 Qt 5.14.1 PyQt 5.14.1
Platform: Windows 10
Flags: frz=True ao=True sv=2
Add-ons, last update check: 2020-10-02 14:31:51

Caught exception:
Traceback (most recent call last):
  File "C:\Users\pacia\AppData\Roaming\Anki2\addons21\24411424\custom_shortcuts.py", line 143, in <lambda>
    (config_scuts["reviewer choice 3"], lambda: self._answerCard(3)),
  File "C:\Users\pacia\AppData\Roaming\Anki2\addons21\1672712021\YesOrNo.py", line 61, in AKR_answerCard
    ease = remap[count][ease]
KeyError: 8
```

**Comment by brownbat** [comment]
Sorry for the slow reply, I've had a little trouble duplicating this one. Something odd is going on with that KeyError: 8 line. 

Do you have any other add ons that might affect buttons or answers?

**Comment by aPaci95** [comment]
Yes, it may be rememorize buttons? It adds more buttons that bind to 5, 6, 7 and 8 key

**Comment by brownbat** [comment]
Hmm, yeah, from those results it looks like it's rewriting all the answers to "8." I won't be able to distinguish between "Pass" and "Fail" if all the answers are overwritten internally as the same number.

I really want all these button add-ons to play nice together. So I built a new interface/hook to Anki's main program that all the button add ons can use, to make it easier for everybody to all use the same system.

[I flagged that hook on the ReMemorize GitHub page](https://github.com/lovac42/ReMemorizeButtons/issues/13) a while back, hoping that project would adopt it, but it doesn't look like it's had any updates for over a year.

ReMemorize is popular, a lot of people have asked about compatibility. I really wish I could get them to work. I'm just worried that I'm running out of ways to fix compatibility on my end only...

I'll keep thinking about it. If I get more time I'll try digging more through ReMemorize's code, maybe there's a patch I can submit over there, or I can fork it or something. But it will be a lot to dig through so will take me a bit.

Sorry for the inconvenience in the meantime.

**Comment by aPaci95** [comment]
This new hook that you written sounds amazing, thank you very much! I'm looking forward to the day in which every addon will work perfectly without incompatibility with each other!!

**Comment by brownbat** [comment]
I *think* I found a fix. I haven't tested it with ReMemorize Buttons though. Does that have an install link through AnkiWeb or do you just have to install it by sideloading it? 

Be a huge favor if you could try the latest update and report back.

**Comment by brownbat** [comment]
Closing for now, but reopen if that didn't actually solve it. Thanks for the report!
