### ISSUE TITLE
Deck menu options are not appearing.

### ISSUE THREAD

**Issue by CuriosusTuberosum** [brownbat/autoEaseFactor#19]
Hello, Thank you so much for the add-on! there is only one weird problem which is as simple as it is stated in the title (i.e.  import ease factors, export ease factors, and adjust ease factors using the algorithm outside review), I also hope I am not misunderstanding what deck menu options mean, aren't they the ones accessed by clicking on the cog adjacent to the deck's name?

**Comment by brownbat** [comment]
Hmm. You should have a menu like this: 
![image](https://user-images.githubusercontent.com/26754/95996519-c1414080-0e00-11eb-8df4-2adbb1e0dee1.png)

I can confirm it works in Anki 2.1.26 and above (except for the Simulator where I'm still fixing an import issue with and plugging in)... 

Which version of Anki are you using?

**Comment by CuriosusTuberosum** [comment]
Here is the screenshot I forgot to attach. I use Anki 2.1.29.
![image](https://user-images.githubusercontent.com/61952048/96120758-5458a400-0eef-11eb-936d-20d5fae91419.png)

**Comment by brownbat** [comment]
Please give the latest update a try.

EDIT: Closing for now, but reopen if you see any new issues. Thanks for reporting this!

**Comment by CuriosusTuberosum** [comment]
Thanks a ton brownbat! it's fixed!
