### ISSUE TITLE
stop working

### ISSUE THREAD

**Issue by fearls1990** [brownbat/autoEaseFactor#20]
HI after yesterday's update, your addon stop working, I've tried to reinstall but didn't help. Thanks

**Comment by brownbat** [comment]
Sorry to hear that! Which version of Anki do you use? Do you get any error message?

**Comment by brownbat** [comment]
Looks like 2.1.15 is not working.

Confirmed working:
2.1.21, 2.1.26, 2.1.33, 2.1.35.

I don't think I can support versions below 2.1.21 and hope to keep up with releases. I'll make that more clear on the Ankiweb page. 

Sorry if you need to stay on older versions, but highly recommend you upgrade to a more recent stable release if at all possible, at least 2.1.26. There are a lot of better features under the hood to keep everything more stable.

If you are tied to earlier versions, I do include the .ankiaddon files here, which you could use to re-install an earlier version directly if absolutely necessary:
https://github.com/brownbat/autoEaseFactor/commits/moving-average-refactor/autoEaseFactor.ankiaddon

That might be another solution.

If you let me know which version works for your setup, maybe I can include that as a branch on ankiweb.

Thanks for the feedback, let me know if there's an earlier version that works for you, or if I'm misdiagnosing your issue.
