### ISSUE TITLE
Initial "success" value

### ISSUE THREAD

**Issue by mcampbell** [brownbat/autoEaseFactor#30]
The initial right/wrong smoothed moving average seems odd to me.  When I have a card that I've never seen, and somehow get the correct answer the first time I answer, the initial success value is 0.9125.  (I have the deck configured to converge to .90)

How is that value picked; based on my initial convergence figure?  It seems 100% right, given that I've seen it once and got it right once makes more sense. 

bug?  user error?

**Comment by brownbat** [comment]
Ah, moving averages can be a little wonky when you first start out with no seed data. Alternating pass-fail becomes really dependent on which answer came first, so PFPFPF is way different from FPFPFP.

To smooth this out the algorithm adds a "zeroth" review where you were (target) percent correct. In your case you came out of the gate with 90%, your success bumped it up just a bit from there.

So a fail doesn't quite go all the way to 0% right off, and a success doesn't go all the way to 100% right off. This anchoring is a little ad hoc, but just another way to prevent very wild swings early on in moving average calculations.

**Comment by mcampbell** [comment]
Thanks; that was my suspicion.  I work with stock data and eat EMA's all the time so I'm familiar with the seed value issue.  Thanks!  

Love the plugin; It's made my Anki experience way more automated and fun.
