### ISSUE TITLE
How to configure the add-on?

### ISSUE THREAD

**Issue by sautille** [brownbat/autoEaseFactor#52]
I'm probably missing something but just wanted to know -- in the `README`, it says "There are a few options that can be configured by editing the addon" -- I can't seem to find any options either from clicking "Tools" or "Tools --> Addons", or "Preferences" -- is there a file that needs to be manually edited? If so, where would it be located? (Apologies in advance if the question is uninformed!)

**Comment by brownbat** [comment]
Hmm, if you hit Tools > AddOns > (select AutoEaseFactor) you *should* be able to then click on "Config" on the right to open up the config file.

Let me know if that's not working for you.

(Also, are you installing using the add-on code, from ankiweb, or are you installing manually from github by any chance?)

**Comment by sautille** [comment]
hey, thanks for taking a look! I installed it through the add-on code, but I don't think the option is showing up in the dropdown for me:
<img width="439" alt="Screen Shot 2021-05-11 at 4 12 42 PM" src="https://user-images.githubusercontent.com/8596457/117878486-d46f9e00-b273-11eb-9f8e-a106b81131c2.png">

**Comment by brownbat** [comment]
Yeah, that looks right. Click "Add-ons" halfway down. It's below "Empty Cards..." and above "Manage Note Types."

![image](https://user-images.githubusercontent.com/26754/117879014-6b3c5a80-b274-11eb-8f29-04831e1bb0af.png)

Then click "Config" on the lower right.

![image](https://user-images.githubusercontent.com/26754/117879084-85763880-b274-11eb-8ec1-bb85fc63ee29.png)

**Comment by sautille** [comment]
oooh, gotcha, thank you!! I'll add a PR to add this to the `README`
