### ISSUE TITLE
Question: Does the Plugin Update the Ease Factor From Reviews on Mobile?

### ISSUE THREAD

**Issue by bytesource** [brownbat/autoEaseFactor#60]
Hi, 

I'm mostly doing reviews on AnkiDroid. I know that this app doesn't support Anki plugins. 

However, does autoEaseFactor update its data once opened and synced on the desktop (so that the updated ease factor will be available on the next review on mobile)?

Cheers,

Stefan

**Comment by whnr** [comment]
I’d like to pile onto the issue with asking about ankiweb as well.
A note in the readme would be awesome!

**Comment by RisingOrange** [comment]
Yes, but you have to trigger the ease factor recalculation manually for each deck. Click on the cog symbol next to a deck and choose "Adjust Ease Factors To Performance". When you do this and then synch, the ease factors will also get changed on mobile and ankiweb. 

In a future version of the add-on you probably won't have to do this and it will be done automatically each time you use the desktop version of Anki.

See this thread for more information: https://github.com/brownbat/autoEaseFactor/issues/7

**Comment by bytesource** [comment]
Glad to hear that I can use autoEaseFactor on mobile. 

Just to make sure I understood the steps to make this work correctly:

1. Learn on mobile as usual
1. Open Anki on desktop
1. For each deck that should work with autoEaseFactor on multiple devices do the following:
    1. **Click** the gear icon next to the deck
    1. **Click** `Adjust Ease Factors to Performance`
    1. **Click** Sync in the top menu

After this, the adjusted ease factors are saved in Anki's database for that deck and therefore are available on any other device.

As for as I know, autoEaseFactor gets all the data it needs from a deck's history log (revlog table?). 
 
This would mean that the next time on mobile, a deck's learning progress is captured in the history log, but ease factors are not adjusted until I go through the above steps again.

Is this correct? 

Cheers, 

Stefan

**Comment by RisingOrange** [comment]
Yes, this is correct. Just make sure to synchronize the devices between step 1 and step 2.

**Comment by bytesource** [comment]
Great! Thanks a lot!
